server:
  port: 9999
spring:
  application:
    name: activiti-workflow
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: gaofei
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/process/
    history-level: full
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.gaofei.activiti.domain